[project]
name = "100-python-projects"
version = "0.5.0"
description = "100 python projects for practice"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.124.0",
]
